config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :create, :destroy] do
          resources :comments, only: [:index, :create, :destroy]
        end
      end
    end
  end
  
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :manage, User, id: user.id
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comments_counter
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_likes_counter
  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_counters
  # after_destroy :update_counters

  def update_counters
    user.increment!(:posts_counter)
    # user.decrement!(:posts_counter)
  end

  def most_recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  :confirmable
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 5)
    posts.order('created_at desc').limit(limit)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    post = user.posts.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      render json: { message: 'Comment deleted.' }
    else
      render json: { error: 'Comment not deleted.' }
    end
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @user.comments.new(post: @post, text: params[:text])
    if @comment.save
      render json: { message: 'Comment created.' }
    else
      render json: { error: 'Comment not created.' }
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @posts = Post.all
    @user = User.find(params[:user_id])
    render json: @posts
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
    render json: @post
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.user_id = current_user.id
    if @post.save
      render json: @post
    else
      render json: { error: 'Post not created.' }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      render json: { message: 'Post deleted.' }
    else
      render json: { error: 'Post deletion failed.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  def index
    @users = User.all
    if @users
      render json: @users
    else
      render json: { error: 'Users not found' }
    end
  end

  def show
    if @user
      render json: @user
    else
      render json: { error: 'User not found' }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, alert: 'You are not authorized to access this page.'
  end
  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :photo, :bio, :email, :password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
    flash[:notice] = 'Comment successfully deleted.'
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @user.comments.new(post: @post, text: params[:text])
    if @comment.save
      redirect_to user_posts_path(@user, @post)
    else
      render 'new'
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(user: @user, post: @post)
    @like.save
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @posts = Post.all
    @user = User.find(params[:user_id])
  end

  def show
    @post = User.find(params[:user_id]).posts.find(params[:id])
  end

  def new
    @post = Post.new
    user_id = params[:user_id].to_i
    return if current_user.id == user_id
    authorize! :create, @post
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_posts_path(current_user, @post)
    else
      render 'new'
    end
  end

  def destroy
    user = current_user
    @post = Post.find_by(id: params[:id], user_id: params[:user_id])
    @post.comments.destroy_all
    @post.likes.destroy_all
    if @post.destroy
      flash[:notice] = 'Post deleted '
    else
      flash[:alert] = 'post deletion failed'
    end
    redirect_to user_posts_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_new.html.erb
<div>
  <p>Add new comment</p>
  <%= form_with url: user_post_comments_path(@post.user, @post) do |f| %>
    <div class="enter-comment">
      <%= f.text_area :text, placeholder: "enter your comment", class:"text-area" %> 
      <%= f.submit 'Add comment', class:"cmnt-btn" %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='main-container'>
    <%= render 'navbar/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<div class='header_signout_button'> 
    <% if current_user %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        <%= current_user.name%>
    <%end%>
</div>

app/views/posts/index.html.erb
<div class = "container">
    <div class = "user-row">
        <div class = "photo">
        <% if @user.photo%>
        <%= image_tag @user.photo %>
    <%end%>

        </div>
        <div class = "intro-details">
            <p class = "user-name"><%= @user.name %></p>
            <p class = "post-counter">Number of posts:<%= @user.posts_counter %></p>
        </div>
    </div>

    <div class = 'user-post-links'>
        <button><%= link_to 'Create New Post', new_user_post_path %></button>
        <button><%= link_to 'Back to users', root_path %></button>
    </div>


    <% @user.posts.includes([:user]).each do |p| %>
        <div class = "post-row">
            <p class ="post-title"> <%= p.title%></p>
            <p class ="post-text"><%= p.text%></p>
            
            <div class="user-post-footer">
            
                <button><%= link_to 'view post', user_post_path(@user, p)%></button>
                 <% if can? :destroy, p%>
                <%= button_to 'Delete Post', user_post_path(@user, p), method: :delete, data: { turbo: false} %>
                <%end%>

                <p>Comments: <%= p.comments_counter%>, Likes: <%= p.likes_counter%></p>
            </div>
        </div>
        <div class="comment-section">
            <% p.most_recent_comments.includes([:user]).each do |c|%>
                    <P><%= c.user.name + ": " + c.text%></P>
            <% end %>
        </div>

    <%end%>

</div>

app/views/posts/new.html.erb
<div class= "new-post-container">
  <%= form_with model: @post, url: user_posts_path, data: { turbo: false }  do |form| %>
    <h4> Create your Post</h4>
    <p>
      <%= form.text_field :title, placeholder: "Enter post Title", class: "new-post-text" %>
    </p>
    <p>
      <%= form.text_area :text, placeholder: "Enter post description", class: "new-post-text" %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %> 
</div>

app/views/posts/show.html.erb
<div class = "container">
    <div class = "post-container">
        <div class="post-header">
            <p>
                <%= @post.title %> by
                <%= @post.user.name%>
            </p>
            <p class = "post-text">
                <%= @post.text %>
            </p>
            <div class="ind-post-footer">
                <%= button_to 'Like', user_post_likes_path(@post.user, @post) %>
                <p>
                    Comments: <%= @post.comments_counter %>,Likes: <%= @post.likes_counter %>
                </p>
            </div>
        </div>


    </div>
    <%= render '/comments/new' %>
    <div class="comment-section">
        <% @post.most_recent_comments.includes([:user]).each do |c|%>
            <p><%= c.user.name + ": " + c.text%></p>
             <% if can? :destroy, c %>
            <%= button_to "Remove", user_post_comment_path(current_user.id, @post.id, c.id), method: :delete, data: {turbo: false}%>
           <%end%>
        <%end%>
    </div>

    <div class='post-footer'>
        <button><%= link_to 'Back to posts', user_posts_path(@post.user) %></button> 
        <button><%= link_to 'Back to users', root_path %></button>
    </div>
    
</div>

app/views/users/index.html.erb
<div class = "container">

<% @user.each do |p| %>
<div class = "user-row">
    <div class = "photo">
        <% if p.photo%>
                <%= image_tag p.photo %>
            <% end %>

    </div>
    <div class = "u-intro-details">
       <p class = "u-user-name"> <%= link_to p.name, p %> </p>
       <div class = "u-post-counter">
            <button> <%= link_to 'View profile', user_path(p) %></button>
            <p>Number of posts:  <%= p.posts_counter %></p>
       </div>
    </div>    
</div>

<%end%>
</div>

app/views/users/show.html.erb
<div class = "container">
    <div class = "user-row">
        <div class = "photo">
        <% if @user.photo%>
        <%= image_tag @user.photo %>
    <% end %>

        </div>
        <div class = "intro-details">
            <p class = "user-name"><%= @user.name %></p>
            <p class = "user-post-counter">Number of posts:<%= @user.posts_counter %></p>
        </div>
    </div>
    <div class = "bio">
        <p> Bio</p>
        <p><%= @user.bio %></p>
    </div>
    <% @user.recent_posts.each do |p| %>
        <div class = "post-row">
            <p class ="post-title"> <%= p.title%></p>
            <p class ="post-text"><%= p.text%></p>
            <p class="posts-footer">
                <button> <%= link_to 'View Post', user_post_url(@user, p) %></button>
                Comments: <%= p.comments_counter%>, Likes: <%= p.likes_counter%>
            </p>
            
        </div>
    <%end%>
    <p class="posts-link">
        <button><%= link_to 'See all posts', user_posts_path(@user), class: "btn-link" %></button>
    </p>
</div>